// ============================================================
//  FuerteAlMedio — products.js
//
//  COMPLETAR: precio (pesos uruguayos) y destacado (true/false)
//  tipo: "11" = Fútbol 11 | "5" = Fútbol 5 | "Sala" = Futsal
// ============================================================
const talles = [39, 40, 41, 42, 43, 44, 45];
const productos = [

  // NIKE — Air Zoom Mercurial Vapor XV
  { id: "NK-AZMVXV-11-001", marca: "Nike", modelo: "Air Zoom Mercurial Vapor XV", color: "Original", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Air_Zoom_Mercurial_Vapor_XV/Nike_Air_Zoom_Mercurial_Vapor_XV${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-AZMVXV-11-002", marca: "Nike", modelo: "Air Zoom Mercurial Vapor XV", color: "Rosado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 3}, (_, i) => `img/Nike_Air_Zoom_Mercurial_Vapor_Rosado/Nike_Air_Zoom_Mercurial_Vapor_Rosado${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Air Zoom Mercurial Superfly
  { id: "NK-AZMSF-11-001", marca: "Nike", modelo: "Air Zoom Mercurial Superfly", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 3}, (_, i) => `img/Nike_Air_Zoom_Mercurial_Superfly_Blanco/Nike_Air_Zoom_Mercurial_Superfly_Blanco${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Superfly 7 Elite
  { id: "NK-SF7-11-001", marca: "Nike", modelo: "Superfly 7 Elite", color: "Rosado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Superfly_7_Elite_Rosado/Nike_Superfly_7_Elite_Rosado${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-SF7-11-002", marca: "Nike", modelo: "Superfly 7 Elite", color: "Rosado y Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Superfly_7_Elite_P&B/Nike_Superfly_7_Elite_P&B${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-SF7-11-003", marca: "Nike", modelo: "Superfly 7 Elite", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Superfly_7_Elite_Naranja/Nike_Superfly_7_Elite_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-SF7-11-004", marca: "Nike", modelo: "Superfly 7 Elite", color: "Arcoiris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Superfly_7_Elite_Arcoiris/Nike_Superfly_7_Elite_Arcoiris${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-SF7-11-005", marca: "Nike", modelo: "Superfly 7 Elite", color: "Blanco y Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Superfly_7_Elite_B&W/Nike_Superfly_7_Elite_B&W${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-SF7-11-006", marca: "Nike", modelo: "Superfly 7 Elite", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Superfly_7_Elite_Azul/Nike_Superfly_7_Elite_Azul${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Vapor 14 Elite
  { id: "NK-V14-11-001", marca: "Nike", modelo: "Vapor 14 Elite", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Vapor_14_Elite_Naranja/Nike_Vapor_14_Elite_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-002", marca: "Nike", modelo: "Vapor 14 Elite", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Vapor_14_Elite_Azul/Nike_Vapor_14_Elite_Azul${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-003", marca: "Nike", modelo: "Vapor 14 Elite", color: "Arcoiris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 8}, (_, i) => `img/Nike_Vapor_14_Elite_Arcoiris/Nike_Vapor_14_Elite_Arcoiris${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-004", marca: "Nike", modelo: "Vapor 14 Elite", color: "Blanco y Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_BlancoVerde/Nike_Vapor_14_Elite_BlancoVerde${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-005", marca: "Nike", modelo: "Vapor 14 Elite", color: "Celeste", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Celeste/Nike_Vapor_14_Elite_Celeste${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-006", marca: "Nike", modelo: "Vapor 14 Elite", color: "Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Verde/Nike_Vapor_14_Elite_Verde${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-007", marca: "Nike", modelo: "Vapor 14 Elite", color: "Celeste y Amarillo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_CelesteAmarillo/Nike_Vapor_14_Elite_CelesteAmarillo${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14-11-008", marca: "Nike", modelo: "Vapor 14 Elite", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Blanco/Nike_Vapor_14_Elite_Blanco${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Vapor 14 Elite Botita
  { id: "NK-V14B-11-001", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Vapor_14_Elite_Naranja_Botita/Nike_Vapor_14_Elite_Naranja_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-002", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Vapor_14_Elite_Azul_Botita/Nike_Vapor_14_Elite_Azul_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-003", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Arcoiris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Arcoiris_Botita/Nike_Vapor_14_Elite_Arcoiris_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-004", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Blanco y Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_BlancoVerde_Botita/Nike_Vapor_14_Elite_BlancoVerde_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-005", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Celeste", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Celeste_Botita/Nike_Vapor_14_Elite_Celeste_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-006", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Blanco_Botita/Nike_Vapor_14_Elite_Blanco_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-007", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Celeste y Amarillo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_CelesteAmarillo_Botita/Nike_Vapor_14_Elite_CelesteAmarillo_Botita${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V14B-11-008", marca: "Nike", modelo: "Vapor 14 Elite Botita", color: "Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_14_Elite_Verde_Botita/Nike_Vapor_14_Elite_Verde_Botita${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Vapor 13 Elite
  { id: "NK-V13-11-001", marca: "Nike", modelo: "Vapor 13 Elite", color: "Rosado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_13_Elite_Rosado/Nike_Vapor_13_Elite_Rosado${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V13-11-002", marca: "Nike", modelo: "Vapor 13 Elite", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_13_Elite_Azul/Nike_Vapor_13_Elite_Azul${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V13-11-003", marca: "Nike", modelo: "Vapor 13 Elite", color: "Blanco y Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_13_Elite_B&W/Nike_Vapor_13_Elite_B&W${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V13-11-004", marca: "Nike", modelo: "Vapor 13 Elite", color: "Rosado y Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_13_Elite_P&B/Nike_Vapor_13_Elite_P&B${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V13-11-005", marca: "Nike", modelo: "Vapor 13 Elite", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_13_Elite_Naranja/Nike_Vapor_13_Elite_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-V13-11-006", marca: "Nike", modelo: "Vapor 13 Elite", color: "Arcoiris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Vapor_13_Elite_Arcoiris/Nike_Vapor_13_Elite_Arcoiris${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Mercurial Vapor R9
  { id: "NK-MVR9-11-001", marca: "Nike", modelo: "Mercurial Vapor R9", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Mercurial_Vapor_R9_Blanco/Nike_Mercurial_Vapor_R9_Blanco${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MVR9-11-002", marca: "Nike", modelo: "Mercurial Vapor R9", color: "Gris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Mercurial_Vapor_R9_Gris/Nike_Mercurial_Vapor_R9_Gris${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MVR9-11-003", marca: "Nike", modelo: "Mercurial Vapor R9", color: "Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Mercurial_Vapor_R9_Negro/Nike_Mercurial_Vapor_R9_Negro${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MVR9-11-004", marca: "Nike", modelo: "Mercurial Vapor R9", color: "Gris y Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Mercurial_Vapor_R9_GrisV/Nike_Mercurial_Vapor_R9_GrisV${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Mercurial R9
  { id: "NK-MR9-11-001", marca: "Nike", modelo: "Mercurial R9", color: "Rojo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 5}, (_, i) => `img/Nike_Mercurial_R9_Rojo/Nike_Mercurial_R9_Rojo${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MR9-11-002", marca: "Nike", modelo: "Mercurial R9", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 5}, (_, i) => `img/Nike_Mercurial_R9_Azul/Nike_Mercurial_R9_Azul${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Hypervenom Phantom
  { id: "NK-HVP-11-001", marca: "Nike", modelo: "Hypervenom Phantom", color: "Dorado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 7}, (_, i) => `img/Nike_Hypervenom_Phantom_Dorado/Nike_Hypervenom_Phantom_Dorado${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVP-11-002", marca: "Nike", modelo: "Hypervenom Phantom", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 7}, (_, i) => `img/Nike_Hypervenom_Phantom_Naranja/Nike_Hypervenom_Phantom_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVP-11-003", marca: "Nike", modelo: "Hypervenom Phantom", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Hypervenom_Phantom_Blanco/Nike_Hypervenom_Phantom_Blanco${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Hypervenom Skin
  { id: "NK-HVS-11-001", marca: "Nike", modelo: "Hypervenom Skin", color: "Naranja (se activa con agua)", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_Hypervenom_Skin_Naranja/Nike_Hypervenom_Skin_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVS-11-002", marca: "Nike", modelo: "Hypervenom Skin", color: "Azul (se activa con agua)", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 7}, (_, i) => `img/Nike_Hypervenom_Skin_PreAzul/Nike_Hypervenom_Skin_PreAzul${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVS-11-003", marca: "Nike", modelo: "Hypervenom Skin", color: "Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Hypervenom_Skin_Verde/Nike_Hypervenom_Skin_Verde${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVS-11-004", marca: "Nike", modelo: "Hypervenom Skin", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Hypervenom_Skin_Blanco/Nike_Hypervenom_Skin_Blanco${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVS-11-005", marca: "Nike", modelo: "Hypervenom Skin", color: "Rosado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Hypervenom_Skin_Rosado/Nike_Hypervenom_Skin_Rosado${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVS-11-006", marca: "Nike", modelo: "Hypervenom Skin", color: "Anaranjado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Hypervenom_Skin_Anaranjado/Nike_Hypervenom_Skin_Anaranjado${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-HVS-11-007", marca: "Nike", modelo: "Hypervenom Skin", color: "Plateado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Hypervenom_Skin_Plateado/Nike_Hypervenom_Skin_Plateado${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — Magistra
  { id: "NK-MAG-11-001", marca: "Nike", modelo: "Magistra", color: "Gris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Magistra_Gris/Nike_Magistra_Gris${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MAG-11-002", marca: "Nike", modelo: "Magistra", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 7}, (_, i) => `img/Nike_Magistra_Naranja/Nike_Magistra_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MAG-11-003", marca: "Nike", modelo: "Magistra", color: "Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Magistra_Verde/Nike_Magistra_Verde${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-MAG-11-004", marca: "Nike", modelo: "Magistra", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 8}, (_, i) => `img/Nike_Magistra_Blanco/Nike_Magistra_Blanco${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — T90
  { id: "NK-T90-11-001", marca: "Nike", modelo: "T90", color: "Rojo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 7}, (_, i) => `img/Nike_T90_Rojo/Nike_T90_Rojo${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-T90-11-002", marca: "Nike", modelo: "T90", color: "Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/Nike_T90_Negro/Nike_T90_Negro${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-T90-11-003", marca: "Nike", modelo: "T90", color: "Dorado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 8}, (_, i) => `img/Nike_T90_Dorado/Nike_T90_Dorado${i === 0 ? "" : i + 1}.jpeg`) },

  // NIKE — T90 Zoom Air
  { id: "NK-T90Z-11-001", marca: "Nike", modelo: "T90 Zoom Air", color: "Gris y Rojo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_T90_ZoomAir_GrisRojo/Nike_T90_ZoomAir_GrisRojo${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-T90Z-11-002", marca: "Nike", modelo: "T90 Zoom Air", color: "Rojo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_T90_ZoomAir_Rojo/Nike_T90_ZoomAir_Rojo${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-T90Z-11-003", marca: "Nike", modelo: "T90 Zoom Air", color: "Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_T90_ZoomAir_Negro/Nike_T90_ZoomAir_Negro${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-T90Z-11-004", marca: "Nike", modelo: "T90 Zoom Air", color: "Negro y Gris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 3}, (_, i) => `img/Nike_T90_ZoomAir_NegroGris/Nike_T90_ZoomAir_NegroGris${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NK-T90Z-11-005", marca: "Nike", modelo: "T90 Zoom Air", color: "Gris", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 3}, (_, i) => `img/Nike_T90_ZoomAir_Gris/Nike_T90_ZoomAir_Gris${i === 0 ? "" : i + 1}.jpeg`) },

  // ADIDAS — X Crazyfast
  { id: "AD-XCF-11-001", marca: "Adidas", modelo: "X Crazyfast", color: "Azul y Celeste", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_AzulCeleste/Adidas_X_Crazyfast_AzulCeleste${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCF-11-002", marca: "Adidas", modelo: "X Crazyfast", color: "Verde y Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_VerdeBlanco/Adidas_X_Crazyfast_VerdeBlanco${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCF-11-003", marca: "Adidas", modelo: "X Crazyfast", color: "Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Verde/Adidas_X_Crazyfast_Verde${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCF-11-004", marca: "Adidas", modelo: "X Crazyfast", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Naranja/Adidas_X_Crazyfast_Naranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCF-11-005", marca: "Adidas", modelo: "X Crazyfast", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Azul/Adidas_X_Crazyfast_Azul${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCF-11-006", marca: "Adidas", modelo: "X Crazyfast", color: "Rosado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Rosado/Adidas_X_Crazyfast_Rosado${i === 0 ? "" : i + 1}.jpeg`) },

  // ADIDAS — X Crazyfast Cordones
  { id: "AD-XCFC-11-001", marca: "Adidas", modelo: "X Crazyfast Cordones", color: "Azul y Celeste", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_AzulCeleste_Cordones/Adidas_X_Crazyfast_AzulCeleste_Cordones${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCFC-11-002", marca: "Adidas", modelo: "X Crazyfast Cordones", color: "Verde", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Verde_Cordones/Adidas_X_Crazyfast_Verde_Cordones${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCFC-11-003", marca: "Adidas", modelo: "X Crazyfast Cordones", color: "Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Naranja_Cordones/Adidas_X_Crazyfast_Naranja_Cordones${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "AD-XCFC-11-004", marca: "Adidas", modelo: "X Crazyfast Cordones", color: "Rosado", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_X_Crazyfast_Rosado_Cordones/Adidas_X_Crazyfast_Rosado_Cordones${i === 0 ? "" : i + 1}.jpeg`) },

  // NEW BALANCE — Furon Team V8 Elite
  { id: "NB-FTV8-11-001", marca: "New Balance", modelo: "Furon Team V8 Elite", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 8}, (_, i) => `img/NewBalance_FuronTeam_V8_Elite_Blanco/NewBalance_FuronTeam_V8_Elite_Blanco${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTV8-11-002", marca: "New Balance", modelo: "Furon Team V8 Elite", color: "Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/NewBalance_FuronTeam_V8_Elite_Negro/NewBalance_FuronTeam_V8_Elite_Negro${i === 0 ? "" : i + 1}.jpeg`) },

  // NEW BALANCE — Furon Team Speed Control
  { id: "NB-FTSC-11-001", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Gris y Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_GrisAzul/NewBalance_FuronTeam_SpeedCtrl_GrisAzul${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTSC-11-002", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Verde y Naranja", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_VerdeNaranja/NewBalance_FuronTeam_SpeedCtrl_VerdeNaranja${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTSC-11-003", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Rojo", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_Rojo/NewBalance_FuronTeam_SpeedCtrl_Rojo${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTSC-11-004", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_Blanco/NewBalance_FuronTeam_SpeedCtrl_Blanco${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTSC-11-005", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Negro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_Negro/NewBalance_FuronTeam_SpeedCtrl_Negro${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTSC-11-006", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Azul", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_Azul/NewBalance_FuronTeam_SpeedCtrl_Azul${i === 0 ? "" : i + 1}.jpeg`) },
  { id: "NB-FTSC-11-007", marca: "New Balance", modelo: "Furon Team Speed Control", color: "Blanco y Oro", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 9}, (_, i) => `img/NewBalance_FuronTeam_SpeedCtrl_BlancoOro/NewBalance_FuronTeam_SpeedCtrl_BlancoOro${i === 0 ? "" : i + 1}.jpeg`) },

  // NEW BALANCE — Tekela
  { id: "NB-TEK-11-001", marca: "New Balance", modelo: "Tekela", color: "Blanco", tipo: "11", precio: 0, destacado: false, talles: talles,
    imagenes: Array.from({length: 8}, (_, i) => `img/NewBalance_Tekela_Blanco/NewBalance_Tekela_Blanco${i === 0 ? "" : i + 1}.jpeg`) },

  // ─── ADIDAS 26 PREDATOR ELITE ───────────────────────────────────────────────
  {
    id: "AD-26PE-11-001",
    marca: "Adidas",
    modelo: "26 Predator Elite",
    color: "Negro Celeste",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_NegroCeleste/Adidas_26_Predator_Elite_NegroCeleste${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PE-11-002",
    marca: "Adidas",
    modelo: "26 Predator Elite",
    color: "Blanco Rosa",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_BlancoRosa/Adidas_26_Predator_Elite_BlancoRosa${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PE-11-003",
    marca: "Adidas",
    modelo: "26 Predator Elite",
    color: "Negro Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_NegroBlanco/Adidas_26_Predator_Elite_NegroBlanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PE-11-004",
    marca: "Adidas",
    modelo: "26 Predator Elite",
    color: "Rosado",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_Rosado/Adidas_26_Predator_Elite_Rosado${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PE-11-005",
    marca: "Adidas",
    modelo: "26 Predator Elite",
    color: "Gris",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_Gris/Adidas_26_Predator_Elite_Gris${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  // ─── ADIDAS 26 PREDATOR ELITE TONGUE ────────────────────────────────────────
  {
    id: "AD-26PET-11-001",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Azul Verde",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_AzulVerde_Tongue/Adidas_26_Predator_Elite_AzulVerde_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-002",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_Blanco_Tongue/Adidas_26_Predator_Elite_Blanco_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-003",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Negro Celeste",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_NegroCeleste_Tongue/Adidas_26_Predator_Elite_NegroCeleste_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-004",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Negro Gris",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_NegroGris_Tongue/Adidas_26_Predator_Elite_NegroGris_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-005",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Blanco Celeste",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_BlancoCeleste_Tongue/Adidas_26_Predator_Elite_BlancoCeleste_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-006",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Blanco Rojo",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_BlancoRojo_Tongue/Adidas_26_Predator_Elite_BlancoRojo_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-007",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Blanco Rosa",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_BlancoRosa_Tongue/Adidas_26_Predator_Elite_BlancoRosa_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-26PET-11-008",
    marca: "Adidas",
    modelo: "26 Predator Elite Tongue",
    color: "Gris",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_26_Predator_Elite_Gris_Tongue/Adidas_26_Predator_Elite_Gris_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },

  // ─── ADIDAS PREDATOR ACCURACY FG ────────────────────────────────────────────
  {
    id: "AD-PAF-11-001",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Rosado",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_Rosado/Adidas_Predator_Accuracy_FG_Rosado${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-002",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Blanco Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoAzul/Adidas_Predator_Accuracy_FG_BlancoAzul${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-003",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Azul Rosa",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_AzulRosa/Adidas_Predator_Accuracy_FG_AzulRosa${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-004",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Negro Oro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_NegroOro/Adidas_Predator_Accuracy_FG_NegroOro${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-005",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Blanco Oro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoOro/Adidas_Predator_Accuracy_FG_BlancoOro${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-006",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Negro Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_NegroAzul/Adidas_Predator_Accuracy_FG_NegroAzul${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-007",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Blanco Rosa",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoRosa/Adidas_Predator_Accuracy_FG_BlancoRosa${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-008",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Blanco Rojo",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoRojo/Adidas_Predator_Accuracy_FG_BlancoRojo${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAF-11-009",
    marca: "Adidas",
    modelo: "Predator Accuracy FG",
    color: "Gris Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_GrisAzul/Adidas_Predator_Accuracy_FG_GrisAzul${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  // ─── ADIDAS PREDATOR ACCURACY FG TONGUE ─────────────────────────────────────
  {
    id: "AD-PAFT-11-001",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Rosado",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_Rosado_Tongue/Adidas_Predator_Accuracy_FG_Rosado_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-002",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Blanco Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoAzul_Tongue/Adidas_Predator_Accuracy_FG_BlancoAzul_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-003",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Azul Rosa",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_AzulRosa_Tongue/Adidas_Predator_Accuracy_FG_AzulRosa_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-004",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Negro Oro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_NegroOro_Tongue/Adidas_Predator_Accuracy_FG_NegroOro_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-005",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Blanco Oro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoOro_Tongue/Adidas_Predator_Accuracy_FG_BlancoOro_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-006",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Negro Rosa",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_NegroRosa_Tongue/Adidas_Predator_Accuracy_FG_NegroRosa_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-007",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Rosa Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_RosaBlanco_Tongue/Adidas_Predator_Accuracy_FG_RosaBlanco_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-008",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Gris Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_GrisAzul_Tongue/Adidas_Predator_Accuracy_FG_GrisAzul_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-PAFT-11-009",
    marca: "Adidas",
    modelo: "Predator Accuracy FG Tongue",
    color: "Blanco Rojo",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_Predator_Accuracy_FG_BlancoRojo_Tongue/Adidas_Predator_Accuracy_FG_BlancoRojo_Tongue${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },

  // ─── NIKE PHANTOM 6 GXIII ELITE ─────────────────────────────────────────────
  {
    id: "NK-P6GE-11-001",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Azul Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_AzulBlanco/Nike_Phantom_6_GXIII_Elite_AzulBlanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-002",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Naranja Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NaranjaBlanco/Nike_Phantom_6_GXIII_Elite_NaranjaBlanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-003",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Rojo Azul Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_RojoAzulBlanco/Nike_Phantom_6_GXIII_Elite_RojoAzulBlanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-004",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Naranja Verde",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NaranjaVerde/Nike_Phantom_6_GXIII_Elite_NaranjaVerde${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-005",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Naranja Gris",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NaranjaGris/Nike_Phantom_6_GXIII_Elite_NaranjaGris${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-006",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_Azul/Nike_Phantom_6_GXIII_Elite_Azul${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-007",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Celeste Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_CelesteBlanco/Nike_Phantom_6_GXIII_Elite_CelesteBlanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-008",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Naranja Negro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NaranjaNegro/Nike_Phantom_6_GXIII_Elite_NaranjaNegro${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-009",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Negro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_Negro/Nike_Phantom_6_GXIII_Elite_Negro${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-010",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Celeste Oro",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_CelesteOro/Nike_Phantom_6_GXIII_Elite_CelesteOro${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-011",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Negro Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NegroBlanco/Nike_Phantom_6_GXIII_Elite_NegroBlanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-012",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Blanco Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_BlancoAzul/Nike_Phantom_6_GXIII_Elite_BlancoAzul${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-013",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Blanco Celeste",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_BlancoCeleste/Nike_Phantom_6_GXIII_Elite_BlancoCeleste${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-014",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Negro Celeste",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NegroCeleste/Nike_Phantom_6_GXIII_Elite_NegroCeleste${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-015",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Arcoiris",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_Arcoiris/Nike_Phantom_6_GXIII_Elite_Arcoiris${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-016",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Negro Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_NegroAzul/Nike_Phantom_6_GXIII_Elite_NegroAzul${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "NK-P6GE-11-017",
    marca: "Nike",
    modelo: "Phantom 6 GXIII Elite",
    color: "Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Nike_Phantom_6_GXIII_Elite_Blanco/Nike_Phantom_6_GXIII_Elite_Blanco${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },

  // ─── ADIDAS F50 CORDONES ─────────────────────────────────────────────────────
  {
    id: "AD-F50C-11-001",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Negro Verde",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_NegroVerde_Cordones/Adidas_F50_NegroVerde_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-002",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Blanco Rojo",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_BlancoRojo_Cordones/Adidas_F50_BlancoRojo_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-003",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Rosa Violeta",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_RosaVioleta_Cordones/Adidas_F50_RosaVioleta_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-004",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Negro Rojo",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_NegroRojo_Cordones/Adidas_F50_NegroRojo_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-005",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Violeta",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_Violeta_Cordones/Adidas_F50_Violeta_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-006",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Celeste Verde",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_CelesteVerdes_Cordones/Adidas_F50_CelesteVerdes_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-007",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Verde Blanco",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_VerdesBlanco_Cordones/Adidas_F50_VerdesBlanco_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-008",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Blanco Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_BlancoAzul_Cordones/Adidas_F50_BlancoAzul_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-009",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Azul",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 5}, (_, i) => `img/Adidas_F50_Azul_Cordones/Adidas_F50_Azul_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
  {
    id: "AD-F50C-11-010",
    marca: "Adidas",
    modelo: "F50 Cordones",
    color: "Blanco Verde",
    tipo: "11",
    precio: 0,
    destacado: false,
    talles: talles,
    imagenes: Array.from({length: 6}, (_, i) => `img/Adidas_F50_BlancoVerde_Cordones/Adidas_F50_BlancoVerde_Cordones${i === 0 ? "" : i + 1}.jpeg`),
    descripcion: ""
  },
];
